import { useMemo,useState } from 'react'
import { Check,ShoppingBag } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import { patientService } from '../services/patientService'
import { useLoad } from './useLoad'
import LoadingSpinner from '../components/common/LoadingSpinner'
import StatusBadge from '../components/common/StatusBadge'

export default function PharmacyStorePage(){
 const {user}=useAuth(),toast=useToast();
 const {data:prescriptions,loading:prescriptionLoading,error:prescriptionError}=useLoad(()=>user.patientId?patientService.prescriptions(user.patientId):Promise.resolve({data:[]}),[user.patientId]);
 const {data:orders,reload:reloadOrders,loading:ordersLoading}=useLoad(()=>user.patientId?patientService.orders(user.patientId):Promise.resolve({data:[]}),[user.patientId]);
 const [selected,setSelected]=useState({}),[quantities,setQuantities]=useState({}),[address,setAddress]=useState(''),[busy,setBusy]=useState(false);
 const medicines=useMemo(()=>prescriptions.flatMap(p=>(p.medicines||[]).map((medicine,index)=>({key:`${p.id}-${index}`,prescriptionId:p.id,doctorName:p.doctorName||'Care team',issuedAt:p.issuedAt,name:typeof medicine==='string'?medicine:medicine.name||JSON.stringify(medicine)}))),[prescriptions]);
 const chosen=medicines.filter(m=>selected[m.key]);
 async function placeOrder(){if(!user.patientId)return toast('Your sign-in is not linked to a patient record.','error');if(!chosen.length)return toast('Select at least one prescribed medicine to order.','error');if(!address.trim())return toast('Enter a delivery address.','error');setBusy(true);try{const items=chosen.map(m=>({prescriptionId:m.prescriptionId,medicine:m.name,quantity:Number(quantities[m.key]||1)}));await patientService.createOrder({patientId:user.patientId,patientName:user.name,items:JSON.stringify(items),totalAmount:0,deliveryAddress:address.trim()});toast(`${chosen.length} selected medicine${chosen.length===1?'':'s'} ordered.`);setSelected({});setQuantities({});setAddress('');reloadOrders()}catch{toast('Could not submit your medicine order.','error')}finally{setBusy(false)}}
 return <div className="page-stack"><div className="page-title-row"><div><span className="eyebrow">AROGYACARE PHARMACY</span><h1>Medicine orders</h1><p>Select only the prescribed items you need delivered.</p></div></div>{!user.patientId&&<div className="notice">Your account is not linked to a patient record. Contact your hospital to connect it.</div>}{prescriptionError&&<div className="notice error-notice">{prescriptionError}</div>}<div className="content-grid"><section className="panel"><div className="panel-heading"><h2>Prescribed medicines</h2><ShoppingBag/></div>{prescriptionLoading?<LoadingSpinner/>:medicines.length? <div className="select-medicine-list">{medicines.map(m=><article className={`select-medicine ${selected[m.key]?'is-selected':''}`} key={m.key}><label className="medicine-select-label"><input type="checkbox" checked={Boolean(selected[m.key])} onChange={e=>setSelected({...selected,[m.key]:e.target.checked})}/><span className="medicine-check"><Check size={15}/></span><span className="medicine-choice"><b>{m.name}</b><small>From {m.doctorName}{m.issuedAt?` · ${new Date(m.issuedAt).toLocaleDateString()}`:''}</small></span></label>{selected[m.key]&&<label className="quantity-control">Qty<input type="number" min="1" max="99" value={quantities[m.key]||1} onChange={e=>setQuantities({...quantities,[m.key]:Math.max(1,Math.min(99,Number(e.target.value)||1))})}/></label>}</article>)}</div>:<p className="muted">No prescribed medicines are available in this patient profile.</p>}<label className="form-label">Delivery address<textarea rows="3" value={address} onChange={e=>setAddress(e.target.value)} placeholder="House, street, city and postal code" required/></label><div className="order-summary"><span>{chosen.length} medicine{chosen.length===1?'':'s'} selected</span><small>Pricing is not provided by the hospital API.</small></div><button className="button primary" disabled={busy||!chosen.length||!user.patientId} onClick={placeOrder}>{busy?<LoadingSpinner label="Placing order"/>:'Place selected order'}</button></section><section className="panel"><div className="panel-heading"><h2>Order history</h2></div>{ordersLoading?<LoadingSpinner/>:orders.map(o=><div className="order-row" key={o.id}><b>Order #{o.id}</b><StatusBadge status={o.status}/><small>{o.orderDate?new Date(o.orderDate).toLocaleDateString():''} · {o.deliveryAddress}</small></div>)}{!ordersLoading&&!orders.length&&<p className="muted">No medicine orders yet.</p>}</section></div></div>
}
