import { useEffect,useMemo,useState } from 'react'
import { ArrowRight,CalendarDays,ClipboardList,Clock3,HeartPulse,Hospital,Plus,Search,Stethoscope,Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import { api } from '../services/api'
import { appointmentService } from '../services/appointmentService'
import { doctorService } from '../services/doctorService'
import { patientService } from '../services/patientService'
import StatCard from '../components/dashboard/StatCard'
import MetricChart from '../components/dashboard/MetricChart'
import StatusBadge from '../components/common/StatusBadge'
function rows(d){return Array.isArray(d)?d:(d?.content||[])}
export default function PortalHome({role}){const {user}=useAuth(),toast=useToast();const [doctors,setDoctors]=useState([]),[patients,setPatients]=useState([]),[appts,setAppts]=useState([]),[symptom,setSymptom]=useState(''),[spec,setSpec]=useState(''),[busy,setBusy]=useState(true),[apiStatus,setApiStatus]=useState('Checking');useEffect(()=>{let live=true;Promise.allSettled([doctorService.list(),patientService.list({size:100}),appointmentService.list()]).then(([d,p,a])=>{if(!live)return;if(d.status==='fulfilled')setDoctors(rows(d.value.data));if(p.status==='fulfilled')setPatients(rows(p.value.data));if(a.status==='fulfilled')setAppts(rows(a.value.data));else if(a.reason.response?.status!==404)toast('Appointments could not be loaded. Check the hospital API connection.','error');setApiStatus([d,p,a].every(x=>x.status==='fulfilled')?'Online':'Unavailable');setBusy(false)});return()=>{live=false}},[]);const suggestion=/rash|skin|itch|acne/i.test(symptom)?'Dermatology':/chest|heart|pressure|palpitation/i.test(symptom)?'Cardiology':/headache|memory|nerve/i.test(symptom)?'Neurology':/child|baby|fever/i.test(symptom)?'Pediatrics':'';const own=appts.filter(a=>role==='patient'?String(a.patient?.id??a.patientId)===String(user.patientId):role==='doctor'?String(a.doctor?.id??a.doctorId)===String(user.doctorId):true);const filtered=doctors.filter(d=>!spec||d.specialization?.toLowerCase().includes(spec.toLowerCase()));return <div className="page-stack"><div className="welcome-banner"><div><span className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</span><h1>{role==='patient'?`Good day, ${user.name.split(' ')[0]}`:role==='doctor'?`Welcome, ${user.name}`:'Hospital overview'}</h1><p>{role==='patient'?'Let’s make your next step toward feeling better.':role==='doctor'?'Your clinical work, organized in one place.':'A clear view of care operations across your hospital.'}</p></div><div className="welcome-symbol"><HeartPulse size={48}/></div></div>
{role==='patient'&&<><section className="symptom-box"><div><span className="eyebrow">FIND THE RIGHT CARE</span><h2>What can we help you with?</h2><p>Describe a symptom to see a relevant department suggestion.</p></div><div className="symptom-search"><Search size={18}/><input value={symptom} onChange={e=>setSymptom(e.target.value)} placeholder="For example, skin rash or chest pressure"/><Link className="button primary" to={`/patient/discover${suggestion?`?specialization=${encodeURIComponent(suggestion)}`:''}`}>Find care <ArrowRight size={17}/></Link></div>{suggestion&&<div className="suggestion"><span className="pulse-dot"/> Suggested department: <b>{suggestion}</b> <small>Suggestions are based on entered symptoms and are not a medical diagnosis.</small></div>}{!suggestion&&<small className="disclaimer">Suggestions are based on entered symptoms and are not a medical diagnosis.</small>}</section><div className="stat-grid"><StatCard label="My appointments" value={own.length} icon={CalendarDays} detail="In your care timeline"/><StatCard label="Available specialists" value={doctors.length} icon={Stethoscope} detail="Connected clinicians"/><StatCard label="Patient profile" value={user.patientId?'Connected':'Not linked'} icon={HeartPulse} detail={user.patientId?`Record #${user.patientId}`:'Ask the hospital to link your account'}/></div></>}
{role==='doctor'&&<div className="stat-grid"><StatCard label="My appointments" value={own.length} icon={CalendarDays} detail="Scheduled and completed"/><StatCard label="Scheduled today" value={own.filter(a=>a.status==='SCHEDULED'&&String(a.appointmentDate||'').startsWith(new Date().toISOString().slice(0,10))).length} icon={Clock3} detail="Based on your appointment queue"/><StatCard label="Patient records" value={patients.length} icon={Users} detail="Registered with this hospital"/></div>}
{role==='admin'&&<div className="stat-grid"><StatCard label="Specialists" value={doctors.length} icon={Stethoscope} detail="Registered clinicians"/><StatCard label="Patients" value={patients.length} icon={Users} detail="Hospital directory"/><StatCard label="Consultations" value={appts.length} icon={CalendarDays} detail="Appointment records"/><StatCard label="System status" value={apiStatus} icon={HeartPulse} detail="Live hospital API data"/></div>}
<div className="content-grid"><MetricChart title={role==='patient'?'Your appointments':role==='doctor'?'Consultation queue':'Recent appointments'}><div className="table-wrap"><table><thead><tr><th>{role==='patient'?'Clinician':'Patient / clinician'}</th><th>Date & time</th><th>Reason</th><th>Status</th></tr></thead><tbody>{own.slice(0,6).map(a=><tr key={a.id}><td><b>{role==='patient'?a.doctor?.name||`Doctor #${a.doctorId}`:a.patient?.name||`Patient #${a.patientId}`}</b>{role!=='patient'&&<small>{a.doctor?.name}</small>}</td><td>{a.appointmentDate?new Date(a.appointmentDate).toLocaleString():'—'}</td><td>{a.reason||'Consultation'}</td><td><StatusBadge status={a.status}/></td></tr>)}{!own.length&&<tr><td colSpan="4" className="empty-cell">{busy?'Loading appointments…':role==='patient'?'No appointment records are linked to this profile yet.':'No appointment records available. The backend currently does not expose GET /appointments.'}</td></tr>}</tbody></table></div>{role==='patient'&&<Link className="panel-link" to="/patient/discover">Explore doctors <ArrowRight size={16}/></Link>}{role==='doctor'&&<Link className="panel-link" to="/doctor/appointments">Open consultation queue <ArrowRight size={16}/></Link>}</MetricChart><section className="panel care-panel"><div className="panel-heading"><h2>{role==='admin'?'Hospital tools':'Your care, connected'}</h2></div>{role==='admin'?<div className="quick-grid"><Link to="/admin/doctors"><Stethoscope/>Manage doctors</Link><Link to="/admin/patients"><Users/>Patient directory</Link><Link to="/admin/hospitals"><Hospital/>Hospital clinics</Link></div>:role==='patient'?<div className="care-actions"><Link to="/patient/prescriptions"><ClipboardList/><span><b>Digital prescriptions</b><small>Review medicines and clinical notes</small></span><ArrowRight/></Link><Link to="/patient/reports"><HeartPulse/><span><b>SOAP health report</b><small>Fetch your clinical encounter history</small></span><ArrowRight/></Link></div>:<div className="care-actions"><Link to="/doctor/appointments"><CalendarDays/><span><b>Consultation queue</b><small>Review patients and write prescriptions</small></span><ArrowRight/></Link></div>}</section></div></div>}
